// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Balance struct {
	UserID     uuid.NullUUID `json:"user_id"`
	GroupID    uuid.NullUUID `json:"group_id"`
	CreditorID uuid.NullUUID `json:"creditor_id"`
	UpdatedAt  time.Time     `json:"updated_at"`
	Balance    string        `json:"balance"`
}

type Debt struct {
	ID            uuid.UUID `json:"id"`
	Amount        string    `json:"amount"`
	TransactionID uuid.UUID `json:"transaction_id"`
	Debtor        uuid.UUID `json:"debtor"`
	Creditor      uuid.UUID `json:"creditor"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Paid          bool      `json:"paid"`
}

type Group struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
}

type GroupMember struct {
	UserID  uuid.NullUUID `json:"user_id"`
	GroupID uuid.NullUUID `json:"group_id"`
}

type RefreshToken struct {
	Token     string       `json:"token"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	Email     string       `json:"email"`
	UserID    uuid.UUID    `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type Transaction struct {
	ID          uuid.UUID      `json:"id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	AuthorID    uuid.UUID      `json:"author_id"`
	GroupID     uuid.UUID      `json:"group_id"`
}

type User struct {
	ID             uuid.UUID      `json:"id"`
	Name           sql.NullString `json:"name"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	Email          string         `json:"email"`
	HashedPassword string         `json:"hashed_password"`
}
