// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, created_at, updated_at, title, description, author_id, amount)
    VALUES (gen_random_uuid (), NOW(), NOW(), $1, $2, $3, $4)
RETURNING
    id, created_at, updated_at, title, description, author_id, amount
`

type CreateTransactionParams struct {
	Title       string
	Description sql.NullString
	AuthorID    uuid.NullUUID
	Amount      string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.Title,
		arg.Description,
		arg.AuthorID,
		arg.Amount,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.Amount,
	)
	return i, err
}
