# TODO: I think this is right but need to check, followed this guide:
# https://docs.github.com/en/actions/tutorials/publish-packages/publish-docker-images
name: Publish Docker image

# publish a new version when a tag in the format of v* (ex: v1.0) is pushed
# TODO: github action to automatically create incremented tags when PR merged to main with "chore:", "fix:", "patch:", or "feat:" in the title
on:
  push:
    tags: 
      - 'v*' 

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }} #TODO: add these secrets
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: cooperstandard/netzero

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/cooperstandard/netzero
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
